### ISSUE TITLE
[bug] pouch images "" return err

### ISSUE THREAD

**Issue by Letty5411** [alibaba/pouch#190]
**Issue Description**
The following CMD should not return error:
```
pouch images ""
```
**Describe what happened**:
```
#pouch images ""
Error: unknown command "" for "pouch images"
unknown command "" for "pouch images"
```
**Describe what you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
1.
2.
3.

**Anything else we need to know?**:
The same issue for CMD: ps , 
**Environment**:
- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by allencloud** [comment]
Why `pouch images ""` should not return error?
Could you add more explanation here? @Letty5411

**Comment by Letty5411** [comment]
For example : 
```
#docker images ""
REPOSITORY                                              TAG                            IMAGE ID            CREATED             SIZE
reg.docker.alibaba-inc.com/letty_ll/pouch               test5                          6dfe673c0d83        2 weeks ago         708.2 MB
<none>                                                  <none>                         399fa381f288        2 weeks ago         675.4 MB
reg.docker.alibaba-inc.com/letty_ll/pouch               test                           8faf19a55066        2 weeks ago         737.6 MB
```

The purpose of the usage is writing a script like follwing:
```
args=("" "-a" "xxx")
```
args is NULL is a use scenario.

**Comment by wrfly** [comment]
Hello letty, well I don't think you should use docker's reaction to test other software, because it's a design rather than a contradistinction. 

Any quoted arguments should be treated as a single argument to the program, if you modified the arguments I typed, you break the rule.

For example:
```bash
➜  /tmp touch 
touch: missing file operand
Try 'touch --help' for more information.
➜  /tmp touch ""
touch: cannot touch '': No such file or directory
➜  /tmp ls ""
ls: cannot access '': No such file or directory
➜  /tmp cd ""
➜  /tmp cd
➜  ~ 
➜  ~ 
```
Just as I said, either `touch`, `ls`, `cd` treated the `""` as its argument, and returns an error if the program thought the argument is wrong. While the `cd` is special, it will change the directory to your home if received an empty argument. Both `cd ""` and `docker images ""` work "properly" but I considered it as a feature, not a bug.

It's good to add this feature, but I doubt the use scenario you provided, because even docker doesn't support this "scenario":

```bash
➜  ~ docker images -a ubuntu
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
ubuntu              latest              ccc7a11d65b1        3 months ago        120MB
➜  ~ docker images "" -a ubuntu
"docker images" requires at most 1 argument(s).
See 'docker images --help'.

Usage:  docker images [OPTIONS] [REPOSITORY[:TAG]]

List images
➜  ~ 
```

What's your opinion, @allencloud ?

**Comment by Letty5411** [comment]
@wrfly has solved my question, close this issue.

**Comment by allencloud** [comment]
Thanks for your comment. @wrfly We totally agree with you. Please keep enjoying Pouch.
