### ISSUE TITLE
[help wanted] degree some log level from Error to Warn

### ISSUE THREAD

**Issue by HusterWan** [alibaba/pouch#2192]
### Ⅰ. Issue Description

In `pouchd`,  we use service logs to monitor the health of `pouchd` . Some log level setting is not reasonable, just like logs below, i think we should set the log level from `error` to `warn`:

```
Handler for DELETE /v1.23/volumes/a5ea25fd69260defba683fff8e766278e8972c0b570e1c73ea5cea1d8c5a4ccd, client 100.81.193.96:47927 ali api.sigma.alibaba-inc.com returns error: failed to get volume: a5ea25fd69260defba683fff8e766278e8972c0b570e1c73ea5cea1d8c5a4ccd: volume not found: no such volume

Handler for DELETE /v1.24/images/91941dd25226, client @ returns error: Unable to remove the image "sha256:91941dd2522667b882a280c6edf5b9314b9b43cab2fe3e5fd1437c354bd997e8" (must force) - container (fa82609ed3677d4771bfe0c645e9a0c5c61eb61f5531affe1c0e14338232ff4a, et15sqa_011162130243) is using this image

```

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:

- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by fengzixu** [comment]
Setting a regulation about log level is always a reluctant problem. There are some thoughts about it.

#### Error

I prefer to use `Error` to illustrate the critical errors which give some bad impacts on functions. So if you see the logs in `Error` format, that stands for some failures happened in functions.

#### Info

The level called `Info` usually are used for printing useful information which can help users to track some situations when they want to know what happened in the pouch. We must realise that the info printed by `Info` will be probably seen for users. 

#### Debug

This level usually is used for printing info which is beneficial for developers when they want to track some processes in the project.

#### Warn

For `Warn`, I always feel confused. `Warn` stands for some errors which are not critical. But, during our development, whether we should handle this type of errors? In my opinion, if the errors need to be noticed, we should use `Error` level to print them.


That's a part of my thoughts about log level. I am very glad to discuss this problem with others so that I can make some useful contribution to the pouch or my projects. Here is an article was written by myself about log level:  http://littledriver.net/posts/golang-log-level-best-pratice/
