### ISSUE TITLE
[question] Could pouch collect container cpu load?

### ISSUE THREAD

**Issue by hkebao** [alibaba/pouch#2313]
### Ⅰ. Issue Description

I  found that we could not use cadvisor in Kubernetes to collect the container cpu load.

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:

- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by allencloud** [comment]
Could you answer the issue here? we could collect more progress data to fill this issue. And make people know the progress. Thanks. @Starnop

**Comment by Starnop** [comment]
I am sorry, maybe need more time to learn more details about `cadvisor`, and some releated info please refer to :
https://github.com/google/cadvisor/pull/437
https://github.com/google/cadvisor/pull/1188

**Comment by allencloud** [comment]
I think we could collect container cpu load via PouchContainer in Kubernetes via cadvisor? Am I right?
@Starnop 
If the answer is yes. I am afraid that we should support @hkebao to make it as soon as possible.

**Comment by Starnop** [comment]
@allencloud 
In fact, the pouch has nothing to do with the that whether it can be collected or not. Since the pouch rely on containerd, for the cadvisor, all containers created by pouch be equivalent to created by containerd. 

Currently, the cadvisor only collects containers information in `k8s.io` namespace of containerd which cannot be changed. 

In addition, for all I know, `cadvisor`  get taskstats according to cgroup path of container using `netlink` tools, and use formulas ` load(t) = load(t-1) e^(-5/60) + n (1 - e^(-5/60))` to calculate the CPU Load Average.

The last, according to the source code, the caller should set flag `enable_load_reader` to true  to enable collect cpu load. Here's a little hint, if you run `cadvisor` in a container and want to get the data of cpu load, you should set the network of container to be **host**.
```
var enableLoadReader = flag.Bool("enable_load_reader", false, "Whether to enable cpu load reader")
```
@hkebao 
So if you cannot get data of cpu load, maybe sone advices will help you a little:
1. make sure that you have defined the namespace of containerd to `k8s.io`
```
// Notes(ziren): default-namespace is passed to containerd, the default
// value is 'default'. So if IsCriEnabled is true for k8s, we should set the DefaultNamespace
// to k8s.io
flagSet.StringVar(&cfg.DefaultNamespace, "default-namespace", namespaces.Default, "default-namespace is passed to containerd, the default value is 'default'")
```
2. make sure that you have set `true`  with flag `enable_load_reader` 
3. make sure that set `host` to the network of container `cadvisor` if you run `cadvisor` in a container 
3. make sure that cpu loader has been initialized properly, it is necessary to view the logs.

**Comment by fuweid** [comment]
@Starnop could we file PR to cadvisor to support configurable namespace? I think it should support it.

**Comment by Starnop** [comment]
@hkebao Is there still any questions? Please let us know if you have any.  And if not, could you please help close this issue? Thanks. :)

**Comment by Starnop** [comment]
@fuweid I have open an [issue](https://github.com/google/cadvisor/issues/2082) . However, there is no reply. And I have look around the source code, it's not easy to add a parameter due to the non-expandable design. I am afraid it is  difficult to advance this matter for now.
