### ISSUE TITLE
[feature request] run pouchd as a system service

### ISSUE THREAD

**Issue by allencloud** [alibaba/pouch#282]
**Issue Description**

Currently Pouchd is only started manually by `pouchd`.  It cannot be running as a background process like a service on Linux. 

```
root@ubuntu:~# pouchd
INFO[0000] starting containerd                           module=containerd revision=89623f28b87a6004d4b785663257362d1658a729 version=v1.0.0
INFO[0000] setting subreaper...                          module=containerd
INFO[0000] loading plugin "io.containerd.content.v1.content"...  module=containerd type=io.containerd.content.v1
INFO[0000] loading plugin "io.containerd.snapshotter.v1.btrfs"...  module=containerd type=io.containerd.snapshotter.v1
WARN[0000] failed to load plugin io.containerd.snapshotter.v1.btrfs  error="path /var/lib/pouch/containerd/root/io.containerd.snapshotter.v1.btrfs must be a btrfs filesystem to be used with the btrfs snapshotter" module=containerd
INFO[0000] loading plugin "io.containerd.snapshotter.v1.overlayfs"...  module=containerd type=io.containerd.snapshotter.v1
INFO[0000] loading plugin "io.containerd.metadata.v1.bolt"...  module=containerd type=io.containerd.metadata.v1
WARN[0000] could not use snapshotter btrfs in metadata plugin  error="path /var/lib/pouch/containerd/root/io.containerd.snapshotter.v1.btrfs must be a btrfs filesystem to be used with the btrfs snapshotter" module="containerd/io.containerd.metadata.v1.bolt"
INFO[0000] loading plugin "io.containerd.differ.v1.walking"...  module=containerd type=io.containerd.differ.v1
INFO[0000] loading plugin "io.containerd.gc.v1.scheduler"...  module=containerd type=io.containerd.gc.v1
INFO[0000] loading plugin "io.containerd.grpc.v1.containers"...  module=containerd type=io.containerd.grpc.v1
INFO[0000] loading plugin "io.containerd.grpc.v1.content"...  module=containerd type=io.containerd.grpc.v1
INFO[0000] loading plugin "io.containerd.grpc.v1.diff"...  module=containerd type=io.containerd.grpc.v1
INFO[0000] loading plugin "io.containerd.grpc.v1.events"...  module=containerd type=io.containerd.grpc.v1
INFO[0000] loading plugin "io.containerd.grpc.v1.healthcheck"...  module=containerd type=io.containerd.grpc.v1
INFO[0000] loading plugin "io.containerd.grpc.v1.images"...  module=containerd type=io.containerd.grpc.v1
INFO[0000] loading plugin "io.containerd.grpc.v1.leases"...  module=containerd type=io.containerd.grpc.v1
INFO[0000] loading plugin "io.containerd.grpc.v1.namespaces"...  module=containerd type=io.containerd.grpc.v1
INFO[0000] loading plugin "io.containerd.grpc.v1.snapshots"...  module=containerd type=io.containerd.grpc.v1
INFO[0000] loading plugin "io.containerd.monitor.v1.cgroups"...  module=containerd type=io.containerd.monitor.v1
INFO[0000] loading plugin "io.containerd.runtime.v1.linux"...  module=containerd type=io.containerd.runtime.v1
INFO[0000] loading plugin "io.containerd.grpc.v1.tasks"...  module=containerd type=io.containerd.grpc.v1
INFO[0000] loading plugin "io.containerd.grpc.v1.version"...  module=containerd type=io.containerd.grpc.v1
.......
```

We wish that pouchd could be wrapped as a system service, then there will be less interaction in pouchd management.

**Describe what happened**:
Cannot manage pouchd as a service.

**Describe what you expected to happen**:
```
service pouch start/status/restart/stop
```

**How to reproduce it (as minimally and precisely as possible)**:
NONE

**Anything else we need to know?**:
NONE

**Environment**:
- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by janynedoe48** [comment]
On Dec 11, 2017 3:28 AM, "Allen Sun" <notifications@github.com> wrote:

*Issue Description*

Currently Pouchd is only started manually by pouchd. It cannot be running
as a background process like a service on Linux.

root@ubuntu:~# pouchd
INFO[0000] starting containerd
module=containerd revision=89623f28b87a6004d4b785663257362d1658a729
version=v1.0.0
INFO[0000] setting subreaper...                          module=containerd
INFO[0000] loading plugin "io.containerd.content.v1.content"...
module=containerd type=io.containerd.content.v1
INFO[0000] loading plugin "io.containerd.snapshotter.v1.btrfs"...
module=containerd type=io.containerd.snapshotter.v1
WARN[0000] failed to load plugin io.containerd.snapshotter.v1.btrfs
error="path /var/lib/pouch/containerd/root/io.containerd.snapshotter.v1.btrfs
must be a btrfs filesystem to be used with the btrfs snapshotter"
module=containerd
INFO[0000] loading plugin "io.containerd.snapshotter.v1.overlayfs"...
module=containerd type=io.containerd.snapshotter.v1
INFO[0000] loading plugin "io.containerd.metadata.v1.bolt"...
module=containerd type=io.containerd.metadata.v1
WARN[0000] could not use snapshotter btrfs in metadata plugin
error="path /var/lib/pouch/containerd/root/io.containerd.snapshotter.v1.btrfs
must be a btrfs filesystem to be used with the btrfs snapshotter"
module="containerd/io.containerd.metadata.v1.bolt"
INFO[0000] loading plugin "io.containerd.differ.v1.walking"...
module=containerd type=io.containerd.differ.v1
INFO[0000] loading plugin "io.containerd.gc.v1.scheduler"...
module=containerd type=io.containerd.gc.v1
INFO[0000] loading plugin "io.containerd.grpc.v1.containers"...
module=containerd type=io.containerd.grpc.v1
INFO[0000] loading plugin "io.containerd.grpc.v1.content"...
module=containerd type=io.containerd.grpc.v1
INFO[0000] loading plugin "io.containerd.grpc.v1.diff"...
module=containerd type=io.containerd.grpc.v1
INFO[0000] loading plugin "io.containerd.grpc.v1.events"...
module=containerd type=io.containerd.grpc.v1
INFO[0000] loading plugin "io.containerd.grpc.v1.healthcheck"...
module=containerd type=io.containerd.grpc.v1
INFO[0000] loading plugin "io.containerd.grpc.v1.images"...
module=containerd type=io.containerd.grpc.v1
INFO[0000] loading plugin "io.containerd.grpc.v1.leases"...
module=containerd type=io.containerd.grpc.v1
INFO[0000] loading plugin "io.containerd.grpc.v1.namespaces"...
module=containerd type=io.containerd.grpc.v1
INFO[0000] loading plugin "io.containerd.grpc.v1.snapshots"...
module=containerd type=io.containerd.grpc.v1
INFO[0000] loading plugin "io.containerd.monitor.v1.cgroups"...
module=containerd type=io.containerd.monitor.v1
INFO[0000] loading plugin "io.containerd.runtime.v1.linux"...
module=containerd type=io.containerd.runtime.v1
INFO[0000] loading plugin "io.containerd.grpc.v1.tasks"...
module=containerd type=io.containerd.grpc.v1
INFO[0000] loading plugin "io.containerd.grpc.v1.version"...
module=containerd type=io.containerd.grpc.v1
.......

We wish that pouchd could be wrapped as a system service, then there will
be less interaction in pouchd management.

*Describe what happened*:
Cannot manage pouchd as a service.

*Describe what you expected to happen*:

service pouch start/status/restart/stop

*How to reproduce it (as minimally and precisely as possible)*:
1.
2.
3.

*Anything else we need to know?*:

*Environment*:

   - pouch version (use pouch version):
   - OS (e.g. from /etc/os-release):
   - Kernel (e.g. uname -a):
   - Install tools:
   - Others:

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/alibaba/pouch/issues/282>, or mute the thread

**Comment by janynedoe48** [comment]
Please use [fingerprint=ID]

**Comment by janynedoe48** [comment]
Please use plain text in communication with me if possible from this point forward.  I am under the impression that I am going to have to get help in completion of this container.  I am sure I have the info needed to fill in the missing sums.  I need guidance. Hints would be great.  However I could partner and even better somebody with knowledge could assume the rest of the project if there is any interested parties.

Sent from Mail for Windows 10

**Comment by qingyunha** [comment]
A systemd.service unit is required.

**Comment by purplegrape** [comment]
source rpm packed by me ,hope it useful,many thanks!
http://47.254.16.148/centos/7/source/pouch-0.1.0-dev.20171213.el7.centos.src.rpm
http://47.254.16.148/centos/7/x86_64/pouch-0.1.0-dev.20171213.el7.centos.x86_64.rpm

**Comment by allencloud** [comment]
I will test this soon. @purplegrape 
If this works fine, maybe we can discuss more about how to provide a solution for users out of box.

**Comment by purplegrape** [comment]
FYI.
i use golang package from  http://mirror.go-repo.io/centos/go-repo.repo

**Comment by allencloud** [comment]
I think this has been solved in https://github.com/alibaba/pouch/pull/597. Closing this.
