### ISSUE TITLE
[bug]the pull-image feature does not function well

### ISSUE THREAD

**Issue by ZouRui89** [alibaba/pouch#284]
**Issue Description**

something wrong with pull-image feature

**Describe what happened**:
```
Error: failed to pull image: failed to stat snapshot 
sha256:6dfaec39e726d242fcd42e9fffac82c3079a1aa20fc39420b662507b163ee4da: 
snapshotter not loaded: overlayfs: invalid argument
```
**Describe what you expected to happen**:

pull a image 

**How to reproduce it (as minimally and precisely as possible)**:

1.centos7+go1.9.1+containerd+runc
2.
3.

**Anything else we need to know?**:

**Environment**:
- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by Letty5411** [comment]
# uname -a
Linux p6 3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by swift1911** [comment]
@allencloud 可以更新下install的文档吗

**Comment by allencloud** [comment]
Could you help to polish the installation documents?
Since I have no idea about the exact background of this issue and how to solve this. @swift1911

**Comment by xiaoxubeii** [comment]
Same problem. When i changed pouch home_dir to ext4, the problem was gone. So i think set ftype=1 in xfs would fix it too.

**Comment by eryx** [comment]
+1

同 swift1911 所说，不是 pouch 的问题，但建议 pouch 可以检测这个环境参数，至少在log里有提示；或者更智能点，自动更换另外一种 Storage Driver

**Comment by cxz66666** [comment]
> +1
> 
> 同 swift1911 所说，不是 pouch 的问题，但建议 pouch 可以检测这个环境参数，至少在log里有提示；或者更智能点，自动更换另外一种 Storage Driver

We have no idea about change another backend storage driver, like we can't use `ext` instead of `xfs`. 😢 
[Here](https://github.com/containerd/containerd/issues/1986) is a same question in containerd,  and this [commit](https://github.com/alibaba/pouch/commit/2f6a8269b03d8507872e45cf62d15f7c0bccc9fe) solved this question! Maybe later I will update the `INSTALL.md` to point out it 😄 
So this issue is closed!
