### ISSUE TITLE
optimize Dockerfile to reduce build time

### ISSUE THREAD

**Issue by zzchun** [alibaba/pouch#299]
**Issue Description**
I think Dockerfile should be optimized ,there are three reasons:
first, it's unnecessary to install and configure building environments（eg. install go, make, vim）ervrytime, it is a waste of time;
second, Dockerfile can be more simple, should `From` a base image that contains required softs for building pouch;
third , go get will fail because of GFW， which increases difficulty for a beginner;

**Comment by allencloud** [comment]
> eg. install go, make, vim

I think go and make are essential software in Dockerfile, since they are used to build pouch and execute Makefile target.

For vim, it is only used for debugging, or operational use.

In term of base image, I would suggest developers could customize one for his own. Because, we need to let developers know what is going on when building a pouch image directly.

**Comment by allencloud** [comment]
Closing this. Ping us if more questions.
