### ISSUE TITLE
[bug] hardcoded command  /usr/local/bin/containerd 

### ISSUE THREAD

**Issue by purplegrape** [alibaba/pouch#517]
**Issue Description**
command containerd should read from env $PATH

**Describe what happened**:
# pouchd
Error: fork/exec /usr/local/bin/containerd: no such file or directory
ERRO[2018-01-07 14:04:22.606215287] fork/exec /usr/local/bin/containerd: no such file or directory 
# which containerd
/usr/sbin/containerd

**Describe what you expected to happen**:
command containerd should read from env $PATH

**Anything else we need to know?**:

**Environment**:
- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by wsandin** [comment]
Is this really a bug? I'd be happy to create a PR that checks $PATH to detect the correct binary for containerd. But looking closer into the software source, it seems like it's working as intended, with /usr/local/bin/containerd as the default file path which could be overridden with `--containerd-path`

See: https://github.com/alibaba/pouch/blob/master/main.go#L53

**Comment by allencloud** [comment]
I think the current implementation is not so good. Since by default, containerd path would be conflict with the actual path and default path. 

I think a good way is to use the following sequence to choose containerd:

1. use the user-specified containerd with flag `--containerd-path`;
2. If user does not specify, try to find containerd in $PATH of pouchd's env;
3. If containerd path is not found, try to use the default path pouchd set;

WDYT? @purplegrape @wsandin @skoo87 
If you like this as well, any kind of pull request is welcomed. 😄

**Comment by wsandin** [comment]
I think this makes good sense @allencloud. Will have a look at this!

**Comment by Ace-Tang** [comment]
can we use containerd in $PATH first, and if `--containerd-path` is specified, we will use this specified one, @allencloud @skoo87  ,and I think a configure file is need for pouchd

**Comment by wsandin** [comment]
I plan to use default as $PATH, but could be overridden by --containerd-path flagSet().
I also use /usr/bin/env containerd to call the service via systemd in the vendor directory. Will submit a PR soon!

**Comment by Ace-Tang** [comment]
@wsandin  , I am sorry to misunderstanding the sentence `Will submit a PR soon!` because of my poor English. I understand this as `please give pr fast`, thanks for @allencloud  to remind me, I fell sorry again.

**Comment by wsandin** [comment]
No problems @Ace-Tang, I'm happy there is eager Open-Source contributors like you. Hopefully I get the privilege to contribute to pouchd in another issue.

Cheers!
