### ISSUE TITLE
[feature request] Add a new api "POST /containers/upgrade" to upgrade a container

### ISSUE THREAD

**Issue by allencloud** [alibaba/pouch#823]
### Ⅰ. Issue Description

In some cases, if a user has one old container with old image, user needs to upgrade this container with new image but keep some old things of the old container. For example, the network configuration, the ssh_keys and something else could be kept to the new containers.

More details on demand will be added.

### Ⅱ. Describe what happened
We can not upgrade a container with new image but keep the old configurations and so on.

### Ⅲ. Describe what you expected to happen
We can upgrade a container with new image and keep the old configurations and so on.

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:

- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by yyb196** [comment]
define an method like: `UpgradeContainer(id string, config Config, hostConfig HostConfig)`, whose last two parameters are the same as CreateContainer. 

in the method found the container that will be upgrade by the id, we call it old_container.  Firstly we rename the old_container to a name which adding a suffix `_bak` to the original name and stop the old_container, then compare and merge the Config and HostConfig with those of the old_container and use the merged Config and HostConfig to create a new container, the new container will `VolumeFrom` the old_container. if the new container is running properly after start, we remove the old_container. otherwise we rollback the upgrade. which means we remove the new container and start the old container.

**Comment by HusterWan** [comment]
Since #852 and #923  have merged, i think we can close this issue.

@yyb196 you  can check upgrade command now, if has any problem,  please let me know at any time.
