### ISSUE TITLE
[help wanted] Sirupsen caused installation to fail

### ISSUE THREAD

**Issue by faycheng** [alibaba/pouch#949]
### Ⅰ. Issue Description

```shell
➜  pouch git:(master) ✗ make install
GOOS=linux go build -o pouchd
daemon/mgr/network.go:17:2: case-insensitive import collision: "github.com/alibaba/pouch/vendor/github.com/Sirupsen/logrus" and "github.com/alibaba/pouch/vendor/github.com/sirupsen/logrus"
make: *** [Makefile:23: server] Error 1
```

logrus organization's name was changed to lower-case.If we use the upper-case import :`Sirupsen/logrus`,conflicts would happen due to case sensitivity.

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅴ. Anything else we need to know?

https://github.com/sirupsen/logrus#case-sensitivity
https://github.com/sirupsen/logrus/pull/384

### Ⅵ. Environment:

- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by allencloud** [comment]
Yes, we have suffered this for quite a long time. We are also finding ways to handle this. Do you have any ideas to fix this?

In addition, are you build Pouch in a MacOS? If that, I think there is something we need to config, Since by default, MacOS does not recognize the uppercase or lowercase of directory.

also cc @rudyfly Who is more familiar with this part.

**Comment by faycheng** [comment]
yes,i will make a pull request to correct the import path.
In addition, i did make install in a MacOS.What configurations are required to set up in MacOS?Is there any documents to explain this?
Thanks.

**Comment by allencloud** [comment]
This issue is similar with https://github.com/alibaba/pouch/issues/750
